name: Lint

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    name: Lint
    steps:
    - uses: actions/checkout@master
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.7 
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install libsqlite3-dev
        gem install bundler
        bundle install --jobs 4 --retry 3
    - name: Run RuboCop
      run: bundle exec rubocop
